### ISSUE TITLE
detail.vue页面的css样式 height: 3rem;会导致页面挤压在一起

### ISSUE THREAD

**Issue by YunMengs** [acmenlei/next-ssr-blog#6]
detail.vue页面的css样式 height: 3rem;会导致页面挤压在一起
```css
.markdown-body li {
    height: 3rem;
}
```
